export const SET_HOW_MANY_PHOTOS = "SET_HOW_MANY_PHOTOS";
export const SET_PHOTO_LIST = "SET_PHOTO_LIST";
export const SET_CHECKBOX_PHOTOS = "SET_CHECKBOX_PHOTOS";
export const UNSET_CHECKBOX_PHOTOS = "UNSET_CHECKBOX_PHOTOS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
